/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas_SupervisorCajero;

import CRUD.Consultar;
import CRUD.Insertar;
import static CRUD.Insertar.ID_INMueble;
import Clases.Cliente;
import Clases.Lectura;
import Conexion.Conexion;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Vinicio
 */
public class Registrar_Lectura extends javax.swing.JInternalFrame {
    
    static Connection conn=null;
    public static String ID_Tarifa;
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
private Dimension DimensionBarra = null; 
Color BTNmenuACT =new Color(45,70,94);
Color BTNmenuMouse =new Color(31,51,70);

    public Registrar_Lectura() {
        initComponents();
        QuitarLaBarraTitulo();
        jButton1.setOpaque(true);
        jButton1.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.setContentAreaFilled(false);
       Color X1 =new Color(61,61,61);
       Border thickBorder = new LineBorder(BTNmenuACT, 86);
       jButton1.setBorder(thickBorder);
       jButton2.setBorder(thickBorder);
       
       
       
       ResultSet rs;
        
          TextAutoCompleter textAutoAcompleter = new TextAutoCompleter(medidor);
           Connection conn=null;
           
        try {
            PreparedStatement pstm = Conexion.Enlace(conn).prepareStatement("select * from MEDIDOR ");
               rs= pstm.executeQuery(); 
        
               while( rs.next() )

            {

            textAutoAcompleter.addItem( rs.getString( "IDMEDIDOR" ) );
            
            

            }
        } catch (SQLException ex) {
            Logger.getLogger(Editar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void QuitarLaBarraTitulo()
{ 
Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
DimensionBarra = Barra.getPreferredSize(); 
Barra.setSize(0,0); 
Barra.setPreferredSize(new Dimension(0,0)); 
repaint(); 
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        medidor = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1140, 700));
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 47, 47));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Lectura");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1090, 50));

        jLabel2.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(88, 88, 88));
        jLabel2.setText("Medidor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 340, 56));

        jLabel3.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(88, 88, 88));
        jLabel3.setText("Fecha de Lectura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 340, 56));

        jLabel5.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(88, 88, 88));
        jLabel5.setText("Lectura Actual");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 340, 58));

        jLabel6.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(88, 88, 88));
        jLabel6.setText("Metros Cúbicos Consumidos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 340, 56));

        medidor.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 33)); // NOI18N
        medidor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        medidor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(medidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 456, 56));

        jTextField2.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 33)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 456, 56));

        jTextField3.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 33)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 456, 56));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 33)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 456, 56));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 33)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 456, 56));

        jLabel8.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cancelar");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 250, 50));

        jButton1.setBackground(new java.awt.Color(45, 70, 94));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 250, 57));

        jLabel9.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(88, 88, 88));
        jLabel9.setText("Lectura Anterior ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 340, 56));

        jLabel7.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(88, 88, 88));
        jLabel7.setText("Cobro");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 340, 57));

        jLabel10.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Registrar");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 250, 50));

        jButton2.setBackground(new java.awt.Color(45, 70, 94));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 250, 57));

        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 460, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseWheelMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
Border thickBorder = new LineBorder(BTNmenuMouse, 86);
       jButton1.setBorder(thickBorder);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
Border thickBorder = new LineBorder(BTNmenuACT, 86);
       jButton1.setBorder(thickBorder);
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
Border thickBorder = new LineBorder(BTNmenuMouse, 86);
       jButton2.setBorder(thickBorder);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
    Border thickBorder = new LineBorder(BTNmenuACT, 86);
       jButton2.setBorder(thickBorder);    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
         ResultSet rs;
        int a = Integer.parseInt(jTextField3.getText());
        int b = Integer.parseInt(jTextField2.getText());
        int resta = a-b;
       
        String total= Integer.toString(resta);
        
        jTextField4.setText(total);
        
        if (resta <= 15){
            
            try {
            PreparedStatement pstm = Conexion.Enlace(conn).prepareStatement("select costo from tarifa where idtarifa=1 ");
               rs= pstm.executeQuery(); 
        
               while( rs.next() )

            {

            jTextField5.setText(rs.getString( "costo" ) );
            
            

            }
        } catch (SQLException ex) {
            Logger.getLogger(Registrar_Lectura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           
        }
        
       else
        {
            
        
            if (resta <= 30 ){
            
            try {
            PreparedStatement pstm = Conexion.Enlace(conn).prepareStatement("select costo from tarifa where idtarifa=2 ");
               rs= pstm.executeQuery(); 
        
               while( rs.next() )

            {

            jTextField5.setText(rs.getString( "costo" ) );
            
            

            }
        } catch (SQLException ex) {
            Logger.getLogger(Registrar_Lectura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           
        }
            
            else {
                
            
            
             if (resta <= 75){
            
            try {
            PreparedStatement pstm = Conexion.Enlace(conn).prepareStatement("select costo from tarifa where idtarifa=3 ");
               rs= pstm.executeQuery(); 
        
               while( rs.next() )

            {

            jTextField5.setText(rs.getString( "costo" ) );
            
            

            }
        } catch (SQLException ex) {
            Logger.getLogger(Registrar_Lectura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           
        }
            
             else {
                 
             
            if (resta <= 100){
            
            try {
            PreparedStatement pstm = Conexion.Enlace(conn).prepareStatement("select costo from tarifa where idtarifa=4 ");
               rs= pstm.executeQuery(); 
        
               while( rs.next() )

            {

            jTextField5.setText(rs.getString( "costo" ) );
            
            

            }
        } catch (SQLException ex) {
            Logger.getLogger(Registrar_Lectura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           
        }
            else {
                
            
           
             if (resta >= 101){
            
            try {
            PreparedStatement pstm = Conexion.Enlace(conn).prepareStatement("select costo from tarifa where idtarifa=5 ");
               rs= pstm.executeQuery(); 
        
               while( rs.next() )

            {

            jTextField5.setText(rs.getString( "costo" ) );
            
            

            }
        } catch (SQLException ex) {
            Logger.getLogger(Registrar_Lectura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
           
        }
   }
            } 
             }
             
             
             }
              
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
         try {                                      
             // TODO add your handling code here:
             
             Connection conn=null;
             
             
             String fechaLectura= new SimpleDateFormat("yyyy/MM/dd").format(jDateChooser1.getDate());
             int lecturaAnterior=Integer.parseInt(jTextField2.getText());
             int lecturaActual=Integer.parseInt(jTextField3.getText());
             int metrosCubicos=Integer.parseInt(jTextField4.getText());
             int idMedidor=Integer.parseInt(medidor.getText());
             int idtarifa= Integer.parseInt(jTextField5.getText()); 
             
             Statement stmt;
             ResultSet rsult;
             PreparedStatement pstm1 = Conexion.Enlace(conn).prepareStatement("select idtarifa from tarifa where COSTO = ?");
             pstm1.setInt(1, idtarifa);
             rsult=pstm1.executeQuery();
            
             while (rsult.next()) {
                 ID_Tarifa = rsult.getString("IDTARIFA");
             }
             
             
             try {
                 Connection miConexion = (Connection) Conexion.Enlace(conn);
                 
                 Statement statement = (Statement) miConexion.createStatement();
                 
                 PreparedStatement pstm = Conexion.Enlace(conn).prepareStatement("insert into "
                         + "LECTURA(FECHALECTURA, LECTURAANTERIOR, LECTURAACTUAL, METROSCUBICOS, IDMEDIDOR, IDTARIFA) "
                         + " values(?,?,?,?,?,?)");
                 
                 
                 pstm.setString(1, fechaLectura);
                 pstm.setInt(2, lecturaAnterior);
                 pstm.setInt(3, lecturaActual);
                 pstm.setInt(4, metrosCubicos);
                 pstm.setInt(5, idMedidor);
                 pstm.setString (6, ID_Tarifa);
                 pstm.execute();
                 pstm.close();
                 
                 JOptionPane.showMessageDialog(null, "Datos Agregados");
             } catch (Exception ex) {
                 
             }
             
             
         } catch (SQLException ex) {
            Logger.getLogger(Registrar_Lectura.class.getName()).log(Level.SEVERE, null, ex);
               
            }
         
         reciboNuevo(Double.parseDouble(jTextField5.getText()));
        
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       
    }//GEN-LAST:event_jLabel8MouseClicked


    public void reciboNuevo(Double cobro){
        Consultar nuevo=new Consultar();
        ArrayList<String> obtener=new ArrayList<String>();
        java.util.Date utilDate=new java.util.Date();
        long InMilisegundos=utilDate.getTime();
        
        java.sql.Time sqlTime=new java.sql.Time(InMilisegundos);
         
        try {
            
            int idlec=Integer.parseInt(nuevo.UltimaLectura().get(0));
            String flectura=nuevo.UltimaLectura().get(1);
            String idmed=nuevo.UltimaLectura().get(2);
            int Inzona=Integer.parseInt(nuevo.obtenerZona(idmed));
         
            String fechaVencimiento="";
            if(Inzona>=1||Inzona<=4){
                fechaVencimiento=14+"-"+fVencimiento(flectura)+" "+sqlTime;
            }if(Inzona>=5){
                fechaVencimiento=18+"-"+fVencimiento(flectura)+" "+sqlTime;
                
            }
            Insertar.ingresarRecibo(fechaVencimiento, cobro, idlec);
           
           
        } catch (SQLException ex) {
            Logger.getLogger(Registrar_Lectura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public String fVencimiento(String fecha){
        String result="";
        StringTokenizer st = new StringTokenizer(fecha, "/");
        int anio=Integer.parseInt(st.nextToken());
        int mes=Integer.parseInt(st.nextToken());
        int dia=Integer.parseInt(st.nextToken());
        
        
        if(mes>=1||mes<=11){
            mes=mes+1;
            result=mes+"-"+anio;
        }else{
            mes=1;
            anio=anio+1;
            result=mes+"-"+anio;
        }
        
        
        return result;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField medidor;
    // End of variables declaration//GEN-END:variables
}
